### ISSUE TITLE
Confirm reproduction

### ISSUE THREAD

**Issue by hadzica** [Hsintien-Ng/idinvert_pytorch-reproduced#3] opened 2020-11-29 15:08 UTC
Hello

Can you confirm that you can reproduce the results of the original paper? If yes, do you still have maybe the pretrained encoder, generator and discriminator parameters available? Would be very happy if you can share you insights.

Best,

Amir

**Comment by Hsintien-Ng** [comment] 2020-12-01 04:49
Hey，when I train the encoder from scratch, I cannot reproduce the results as good as the one released in https://github.com/genforce/idinvert_pytorch. Sorry I haven't found the specific reason yet. I will try my best to fix it. 

If you need the pretrained encoder on FFHQ, you can follow the project mentioned above and keep an eye on https://github.com/genforce/genforce, in which the training encoder will be supported in very near future as the authors stated.

**Closed as completed** 2020-12-08 21:21 UTC
